version: "3"

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build: .
    command: gunicorn date_builder.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/_static
      - media_volume:/usr/src/app/_media
      - ./:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.prod

    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: datebuilder # 데이터베이스 이름
    restart: always
    environment:
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql # volume 경로는 왼쪽 그대로 유지

    env_file:
      - ./.env.prod.db

volumes:
  mysql_data:
  static_volume:
  media_volume:
