# Generated by Django 4.2.4 on 2023-09-06 07:34

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
