# Generated by Django 4.2.4 on 2023-09-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='single_pages/files/cafe/'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='single_pages/images/cafe/'),
        ),
    ]
