# Generated by Django 4.2.4 on 2023-09-11 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Play',
        ),
        migrations.AddField(
            model_name='cafe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='single_pages.category'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='single_pages.tag'),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='single_pages.category'),
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.ManyToManyField(blank=True, to='single_pages.tag'),
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='single_pages.category'),
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(blank=True, to='single_pages.tag'),
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
