# Generated by Django 4.2.4 on 2023-09-11 06:03

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0002_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40)),
                ('content', markdownx.models.MarkdownxField()),
                ('head_image', models.ImageField(blank=True, upload_to='single_pages/images/')),
                ('file_upload', models.FileField(blank=True, upload_to='single_pages/files/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cafe',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='single_pages/files/'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='single_pages/images/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='single_pages/files/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='single_pages/images/'),
        ),
    ]
