# Generated by Django 4.2.4 on 2023-09-06 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0003_cafe_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='single_pages.cafe')),
                ('play', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='single_pages.play')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='single_pages.restaurant')),
            ],
        ),
    ]
