# Generated by Django 4.2.4 on 2023-09-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0004_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
