# Generated by Django 4.2.4 on 2023-09-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0004_alter_cafe_file_upload_alter_cafe_head_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='content',
        ),
    ]
