# Generated by Django 4.2.4 on 2023-09-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0005_delete_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
