# Generated by Django 4.2.4 on 2023-09-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
