# Generated by Django 4.2.4 on 2023-09-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0006_alter_cafe_create_date_alter_play_create_date_and_more'),
        ('single_pages', '0009_post_created_at_post_updated_date'),
    ]

    operations = [
    ]
