# Generated by Django 4.2.4 on 2023-09-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0010_merge_20230908_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='updated_date',
        ),
    ]
