# Generated by Django 4.2.4 on 2023-09-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0012_tag_alter_category_options_restaurant_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
