# Generated by Django 4.2.4 on 2023-09-11 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0011_remove_cafe_updated_date'),
        ('single_pages', '0013_alter_category_options_alter_tag_options'),
    ]

    operations = [
    ]
